// app/components/pages/index/VillageCard.vue
<template>
  <NuxtLink :to="`/village?id=${village.id}`" class="spotlight-shadow block">
    <div class="card village-card">
      <header class="card-header village-card-header">
        <p class="card-header-title village-card-header-title text-left">
          {{ village.name }}
        </p>
      </header>
      <div class="card-content">
        <div class="content text-left text-sm">
          <p>状態: {{ status }}</p>
          <p>参加人数: {{ participantStatus }}</p>
          <p v-if="daychangeDatetime">更新: {{ daychangeDatetime }}</p>
          <p>編成: {{ organization }}</p>
          <p>発言可能時間: {{ sayableTime }}</p>
          <p>ダミー役欠け: {{ dummySkill }}</p>
          <p v-if="ageLimit">年齢制限: {{ ageLimit }}</p>
        </div>
      </div>
    </div>
  </NuxtLink>
</template>

<script setup lang="ts">
import type { SimpleVillageView } from '~/lib/api/types'
import { VILLAGE_STATUS } from '~/lib/api/village-status-constants'

const props = defineProps<{
  village: SimpleVillageView
}>()

// 状態表示
const status = computed(() => {
  const villageStatus = props.village.status?.name || ''
  if (props.village.status?.code !== VILLAGE_STATUS.IN_PROGRESS) {
    return villageStatus
  }
  return `${villageStatus} ${nowDate.value}`
})

// 最新日
const latestday = computed(() => {
  const dayList = props.village.day?.day_list || []
  return dayList[dayList.length - 1]
})

// 現在の日付
const nowDate = computed(() => {
  if (props.village.status?.code !== VILLAGE_STATUS.IN_PROGRESS) return null
  return latestday.value ? `${latestday.value.day}日目` : null
})

// 更新日時
const daychangeDatetime = computed(() => {
  const statusCode = props.village.status?.code
  if (
    statusCode === VILLAGE_STATUS.COMPLETED ||
    statusCode === VILLAGE_STATUS.CANCEL
  ) {
    return null
  }
  const datetime = latestday.value?.day_change_datetime
  return datetime ? datetime.substring(0, 16) : null
})

// 参加者数表示
const participantStatus = computed(() => {
  const participantCount = props.village.participant?.count || 0
  const spectatorCount = props.village.spectator?.count || 0
  const maxCapacity = props.village.setting?.capacity?.max || 0

  if (props.village.status?.code === VILLAGE_STATUS.PROLOGUE) {
    return (
      `${participantCount}` +
      `/${maxCapacity}` +
      `${spectatorCount === 0 ? '' : '+' + spectatorCount}`
    )
  } else {
    return (
      `${participantCount}` +
      `${spectatorCount === 0 ? '' : '+' + spectatorCount}`
    )
  }
})

// 発言可能時間
const sayableTime = computed(() => {
  const timeSetting = props.village.setting?.time
  const silentHours = timeSetting?.silent_hours

  if (!silentHours) return '24時間'

  // sayable_startとsayable_endは時刻オブジェクト
  const start = timeSetting?.sayable_start
  const end = timeSetting?.sayable_end

  if (!start || !end) return '24時間'

  const startStr = `${String(start.hour || 0).padStart(2, '0')}:${String(start.minute || 0).padStart(2, '0')}`
  const endStr = `${String(end.hour || 0).padStart(2, '0')}:${String(end.minute || 0).padStart(2, '0')}`

  if (startStr === endStr) return '24時間'

  return `${startStr} - ${endStr}（${24 - silentHours}時間）`
})

// 編成
const organization = computed(() => {
  const maxCapacity = props.village.setting?.capacity?.max
  if (!maxCapacity || !props.village.setting?.organizations?.organization) {
    return '不明'
  }

  const org = props.village.setting.organizations.organization[maxCapacity]
  if (!org) return '不明'

  return Array.isArray(org) ? `${org.length}人: ${org.join(', ')}` : org
})

// ダミー役欠け
const dummySkill = computed(() => {
  return props.village.setting?.rules?.available_dummy_skill ? 'あり' : 'なし'
})

// 年齢制限
const ageLimit = computed(() => {
  const tags = props.village.setting?.tags?.list || []
  return tags.find((t: string) => t.startsWith('R')) || null
})
</script>

<style scoped>
.village-card {
  background-image: url('/image/top-bg.jpg');
  background-size: cover;
  color: white;
  border: 1px solid white;
  border-radius: 4px;
  cursor: pointer;
  transition: transform 0.2s;
}

.village-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
}

.card-header {
  background: rgba(0, 0, 0, 0.3);
  border-bottom: 1px solid white;
  padding: 0.75rem 1rem;
}

.village-card-header-title {
  color: white;
  font-weight: bold;
  font-size: 1.1rem;
}

.card-content {
  padding: 1rem;
  /* background: rgba(0, 0, 0, 0.2); */
}

.content p {
  margin: 0.25rem 0;
  color: white;
  font-size: 0.875rem;
  line-height: 1.25rem;
  padding-top: 5px;
  padding-bottom: 5px;
}

.spotlight-shadow {
  text-decoration: none;
  display: block;
}
</style>

// v2/src/components/village/village-card.tsx
import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { formatDateTime } from '@/utils/datetime'
import type { components } from '@/types/generated/api'
import { VILLAGE_STATUS } from '@/types/village-status'

type SimpleVillageView = components['schemas']['SimpleVillageView']

interface VillageCardProps {
  village: SimpleVillageView
}

export function VillageCard({ village }: VillageCardProps) {
  const statusColor = getStatusColor(village.status.code)

  return (
    <Link
      href={`/village/${village.id}`}
      className="block hover:shadow-lg hover:scale-[1.02] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all duration-200"
    >
      <Card className="overflow-hidden relative cursor-pointer h-full">
        {/* 背景画像 */}
        <div
          className="absolute inset-0 bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: 'url(/firewolf/top-bg.jpg)' }}
        ></div>

        {/* 村名ヘッダー（panel header風） */}
        <div className="relative z-10 bg-black/20 backdrop-blur-sm border-b border-white/20">
          <div className="px-6 py-4 flex justify-between items-center">
            <h3
              className="text-white font-semibold text-lg line-clamp-1"
              style={{
                textShadow:
                  '2px 2px 5px rgba(97, 69, 69, 1), -2px 2px 5px rgba(97, 69, 69, 1), 2px -2px 5px rgba(97, 69, 69, 1), -2px -2px 5px rgba(97, 69, 69, 1)',
              }}
            >
              {village.name}
            </h3>
            <div
              className="px-2 py-1 rounded text-xs font-medium bg-white/30 backdrop-blur-sm text-white"
              style={{
                textShadow:
                  '2px 2px 5px rgba(97, 69, 69, 1), -2px 2px 5px rgba(97, 69, 69, 1), 2px -2px 5px rgba(97, 69, 69, 1), -2px -2px 5px rgba(97, 69, 69, 1)',
              }}
            >
              {village.status.name}
            </div>
          </div>
        </div>

        {/* 村情報コンテンツ */}
        <div className="relative z-10 p-6">
          <div
            className="space-y-2 text-xs text-white leading-relaxed"
            style={{
              textShadow:
                '2px 2px 5px rgba(97, 69, 69, 1), -2px 2px 5px rgba(97, 69, 69, 1), 2px -2px 5px rgba(97, 69, 69, 1), -2px -2px 5px rgba(97, 69, 69, 1)',
            }}
          >
            {/* 参加人数情報 */}
            <div className="text-white">
              参加人数: {village.participant.count} / {village.setting.capacity.max}
              {village.spectator.count > 0 && (
                <span className="text-white/80"> + {village.spectator.count}</span>
              )}
            </div>

            {/* 更新時刻 */}
            <div className="text-white">更新: {getLastUpdateTime(village.day.day_list)}</div>

            {/* 発言可能時間 */}
            <div className="text-white">発言可能時間: {getSayableTime(village.setting.time)}</div>

            {/* 構成 */}
            <div className="text-white">
              編成:{' '}
              {getOrganizationName(
                village.setting.organizations.organization,
                village.participant.count,
                village.setting.capacity.max
              )}
            </div>

            {/* ダミー役欠け */}
            <div className="text-white">
              ダミー役欠け: {getDummySkill(village.setting.rules.available_dummy_skill)}
            </div>

            {/* 年齢制限（該当する場合のみ） */}
            {getAgeLimit(village.setting.tags.list) && (
              <div className="text-white">年齢制限: {getAgeLimit(village.setting.tags.list)}</div>
            )}

            {/* 勝利陣営（終了している場合） */}
            {village.status.is_finished && village.win_camp && (
              <div className="text-white font-medium">勝利陣営: {village.win_camp.name}</div>
            )}

            {/* タグ */}
            {village.setting.tags.list.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-2">
                {village.setting.tags.list.map((tag) => (
                  <span
                    key={tag}
                    className="px-2 py-1 bg-white/20 backdrop-blur-sm text-white rounded text-xs"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </Card>
    </Link>
  )
}

function getStatusColor(statusCode: string): string {
  switch (statusCode) {
    case VILLAGE_STATUS.PROLOGUE:
      return 'bg-green-100 text-green-800'
    case VILLAGE_STATUS.IN_PROGRESS:
      return 'bg-blue-100 text-blue-800'
    case VILLAGE_STATUS.EPILOGUE:
      return 'bg-yellow-100 text-yellow-800'
    case VILLAGE_STATUS.COMPLETED:
      return 'bg-gray-100 text-gray-800'
    case VILLAGE_STATUS.CANCEL:
      return 'bg-red-100 text-red-800'
    default:
      return 'bg-gray-100 text-gray-600'
  }
}

function getOrganizationName(
  organization: { [key: string]: string },
  participantCount: number,
  maxCapacity: number
): string {
  // まず現在の参加人数に対応する構成を探す
  const currentCountKey = String(participantCount)
  if (organization[currentCountKey]) {
    return organization[currentCountKey]
  }

  // なければ最大人数に対応する構成を探す
  const maxCountKey = String(maxCapacity)
  if (organization[maxCountKey]) {
    return organization[maxCountKey]
  }

  // それでもなければ最初のキーの値を返す
  const keys = Object.keys(organization)
  if (keys.length === 0) {
    return '不明'
  }
  return organization[keys[0]] || '不明'
}

function getLastUpdateTime(dayList: { day_change_datetime: string }[] | undefined): string {
  if (!dayList || dayList.length === 0) {
    return '未定'
  }
  const lastDay = dayList[dayList.length - 1]
  return formatDateTime(lastDay.day_change_datetime)
}

function getSayableTime(timeSettings: {
  silent_hours?: number
  sayable_start: { hour?: number; minute?: number }
  sayable_end: { hour?: number; minute?: number }
}): string {
  const silentHours = timeSettings.silent_hours
  if (!silentHours) {
    return '24時間'
  }

  const start = timeSettings.sayable_start
  const end = timeSettings.sayable_end
  const startTime = `${String(start.hour || 0).padStart(2, '0')}:${String(start.minute || 0).padStart(2, '0')}`
  const endTime = `${String(end.hour || 0).padStart(2, '0')}:${String(end.minute || 0).padStart(2, '0')}`

  if (startTime === endTime) {
    return '24時間'
  }

  const activeHours = 24 - silentHours
  return `${startTime} - ${endTime}（${activeHours}時間）`
}

function getDummySkill(available_dummy_skill: boolean): string {
  return available_dummy_skill ? 'あり' : 'なし'
}

function getAgeLimit(tagList: string[]): string | null {
  return tagList.find((tag) => tag.startsWith('R')) || null
}
