// app/pages/charachip.vue
<template>
  <div>
    <section class="bg-gray-50 py-8">
      <div class="container mx-auto px-4">
        <h1 class="mb-4 text-xl font-semibold">
          キャラチップ: {{ charachip ? charachip.name : '' }}
        </h1>

        <!-- キャラチップ情報 -->
        <div v-if="charachip" class="mb-5">
          <p class="text-sm text-gray-700">
            作者: {{ charachip.designer.name }}
          </p>
          <a
            :href="charachip.description_url"
            target="_blank"
            class="text-sm text-blue-600 hover:text-blue-800 hover:underline"
          >
            作者HP
          </a>
          <p class="text-sm text-gray-700">
            名前変更: {{ charachip.is_available_change_name ? '可能' : '不可' }}
          </p>
        </div>

        <div class="text-sm">
          <!-- ローディング表示 -->
          <Loading
            v-if="loadingCharachip"
            :message="'キャラチップを読み込み中...'"
          />

          <!-- キャラクター一覧 -->
          <div
            v-if="!loadingCharachip && charachip"
            class="flex flex-wrap justify-center gap-4"
          >
            <div
              v-for="chara in charachip.chara_list"
              :key="chara.id"
              class="rounded-2xl border border-gray-300 bg-white p-3 text-center shadow-sm"
              style="width: 300px"
            >
              <!-- キャラクター画像（全ての表情を表示） -->
              <div class="mb-2 flex justify-center gap-1">
                <VillageCharaImage
                  v-for="face in chara.face_list"
                  :key="face.type"
                  :chara="chara"
                  :face-type="face.type"
                />
              </div>
              <p class="text-xs">{{ chara.chara_name.name }}</p>
            </div>
          </div>

          <!-- エラー表示 -->
          <div
            v-if="!loadingCharachip && !charachip"
            class="rounded-lg bg-white p-8 shadow"
          >
            <div class="text-center text-gray-500">
              <p>キャラチップが見つかりませんでした</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import type { CharachipView } from '~/lib/api/types'
import VillageCharaImage from '~/components/pages/village/CharaImage.vue'

// ルートパラメータからID取得
const route = useRoute()
const charachipId = computed(() => route.query.id as string | undefined)

// SEO設定
const charachip = ref<CharachipView | null>(null)
useHead({
  title: computed(() =>
    charachip.value ? `キャラチップ: ${charachip.value.name}` : 'キャラチップ'
  )
})

// データ
const loadingCharachip = ref(false)

// データ取得
onMounted(async () => {
  if (!charachipId.value) {
    console.error('キャラチップIDが指定されていません')
    return
  }

  loadingCharachip.value = true
  try {
    const { apiCall } = useApi()
    const response = await apiCall<CharachipView>(
      `/charachips/${charachipId.value}`
    )
    charachip.value = response
  } catch (error) {
    console.error('キャラチップの取得に失敗しました:', error)
    charachip.value = null
  } finally {
    loadingCharachip.value = false
  }
})
</script>

// v2/src/app/(public)/charachip/page.tsx
'use client'

import Link from 'next/link'
import { use, Suspense, lazy } from 'react'
import { useCharachipQuery } from '@/hooks/use-charachip-query'
import { CharaCard } from '@/components/pages/charachip/CharaCard'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'

const LazyCharaCard = lazy(() =>
  import('@/components/pages/charachip/CharaCard').then((module) => ({
    default: module.CharaCard,
  }))
)

interface CharachipDetailPageProps {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}

export default function CharachipDetailPage({ searchParams }: CharachipDetailPageProps) {
  const resolvedSearchParams = use(searchParams)
  const id = resolvedSearchParams.id as string | undefined

  // Hooksは条件分岐の前に呼び出す必要があるため、常に呼び出す
  const charaChipIdNumber = id ? parseInt(id, 10) : 0
  const { data, isLoading, error } = useCharachipQuery(charaChipIdNumber)

  if (!id) {
    return (
      <div className="container mx-auto px-3 md:px-6 py-8">
        <div className="text-center py-12">
          <p className="text-red-600 mb-4">キャラチップIDが指定されていません</p>
          <Link href="/charachip-list">
            <Button variant="outline">キャラチップ一覧に戻る</Button>
          </Link>
        </div>
      </div>
    )
  }

  const charaChipId = parseInt(id, 10)

  if (isNaN(charaChipId)) {
    return (
      <div className="container mx-auto px-3 md:px-6 py-8">
        <div className="text-center py-12">
          <p className="text-red-600 mb-4">無効なキャラチップIDです</p>
          <Link href="/charachip-list">
            <Button variant="outline">キャラチップ一覧に戻る</Button>
          </Link>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container mx-auto px-3 md:px-6 py-8">
        <div className="text-center py-12">
          <p className="text-red-600 mb-4">キャラチップの取得に失敗しました</p>
          <Link href="/charachip-list">
            <Button variant="outline">キャラチップ一覧に戻る</Button>
          </Link>
        </div>
      </div>
    )
  }

  if (isLoading) {
    return (
      <div className="container mx-auto px-3 md:px-6 py-8">
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          <p className="mt-4 text-gray-600">キャラチップ詳細を読み込み中...</p>
        </div>
      </div>
    )
  }

  const charachip = data?.data

  if (!charachip) {
    return (
      <div className="container mx-auto px-3 md:px-6 py-8">
        <div className="text-center py-12">
          <p className="text-gray-600 mb-4">キャラチップが見つかりません</p>
          <Link href="/charachip-list">
            <Button variant="outline">キャラチップ一覧に戻る</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto px-3 md:px-6 py-8">
      <div className="max-w-6xl mx-auto">
        {/* ヘッダー */}
        <div className="mb-6">
          <Link href="/charachip-list">
            <Button variant="outline" className="mb-4">
              ← キャラチップ一覧に戻る
            </Button>
          </Link>
        </div>

        {/* キャラチップ情報 */}
        <Card className="p-8 mb-8">
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold text-gray-900">{charachip.name}</h1>
            <p className="text-lg text-gray-600">作者: {charachip.designer.name}</p>

            {charachip.description_url && (
              <div>
                <a
                  href={charachip.description_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-block text-blue-600 hover:text-blue-800 underline"
                >
                  作者 HP
                </a>
              </div>
            )}

            <div className="text-gray-700 space-y-2">
              <p>キャラクター数: {charachip.chara_list.length}</p>
              <p>名前変更: {charachip.is_available_change_name ? '可能' : '不可'}</p>
            </div>
          </div>
        </Card>

        {/* キャラクター一覧 */}
        <div>
          <h2 className="text-xl font-bold text-gray-900 mb-6">キャラクター一覧</h2>

          {charachip.chara_list.length > 0 ? (
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {charachip.chara_list.map((chara) => (
                <Suspense
                  key={chara.id}
                  fallback={
                    <Card className="p-4 animate-pulse">
                      <div className="space-y-3">
                        <div className="h-5 bg-gray-200 rounded w-3/4 mx-auto"></div>
                        <div className="grid grid-cols-2 gap-2">
                          {[...Array(4)].map((_, i) => (
                            <div key={i} className="w-16 h-16 bg-gray-200 rounded mx-auto"></div>
                          ))}
                        </div>
                      </div>
                    </Card>
                  }
                >
                  <LazyCharaCard chara={chara} />
                </Suspense>
              ))}
            </div>
          ) : (
            <div className="text-center py-12 text-gray-600">
              <p>キャラクターが見つかりません</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
